# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_hcd" "ahci" "usbhid" "usb_storage" ];
  boot.initrd.kernelModules = [ "base" "udev" "shutdown" "resume" "autodetect" "modconf" "block" "filesystems" "keyboard" "fsck" ];
  boot.kernelModules = [ "kvm-intel" "bcm5974" "brcmfmac" "hid_apple" ];
  boot.extraModulePackages = [ ];
  boot.blacklistedKernelModules = [ "bluetooth" "btusb" "bdc_pci" ];

  fileSystems."/" =
    { device  = "/dev/disk/by-uuid/f3758d53-2e42-49b1-acd8-88a42d0fa66a";
      fsType  = "ext4";
      options = "defaults,noatime,discard";
      noCheck = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/67E3-17ED";
      fsType = "vfat";
    };

  swapDevices = [
   { device = "/var/swapfile";
     size = 16384; # in MB
   }
  ];
  
  nix.maxJobs = 8;
  nix.extraOptions = ''
    build-cores = 8
  '';

}
