# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_hcd" "ahci" "usbhid" "usb_storage" ];
  boot.initrd.kernelModules = [ "base" "udev" "shutdown" "resume" "autodetect" "modconf" "block" "filesystems" "keyboard" "fsck" ];
  boot.kernelModules = [ "kvm-intel" "iwlmvm" ];
  boot.extraModulePackages = [ ];
  boot.blacklistedKernelModules = [ "ideapad_laptop" "psmouse" ];

  fileSystems."/" =
    { device  = "/dev/disk/by-label/nixos";
      fsType  = "btrfs";
      options = "noatime,discard,ssd,compress=lzo,space_cache";
      noCheck = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/SYSTEM_DRV";
      fsType = "vfat";
    };

#  swapDevices = [
#   { device = "/var/swapfile";
#     size = 16384; # in MB
#   }
#  ];
  
  nix.maxJobs = 4;
  nix.extraOptions = ''
    build-cores = 4
  '';

}
